### ISSUE TITLE
[Bug]: Endurance platinum trim effect seems to double hunger loss rather than halve it

### ISSUE THREAD

**Issue by HiGuysItsMeSussyBaka** [Fuzss/illagerinvasion#10]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.1

### Notes (Required)

Current behavior: I trimmed a pair of netherite leggings with a platinum silence trim. The effects seem to be me losing hunger twice as fast.
Steps to reproduce
Step 1. Get a pair of leggings/pants
Step 2. Trim them with the platinum material
Step 3. Wear them in survival mode
Expected behavior: Following the steps to reproduce the bug, I should have halved hunger loss rather than doubled.

**Comment by Fuzss** [comment]
Fixed in latest version.
