### ISSUE TITLE
[Crash]: Entering Illusioner Tower or Labyrinth causes crash

### ISSUE THREAD

**Issue by MetaForge** [Fuzss/illagerinvasion#11]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.1

### Notes (Required)

Running Illager Invasion on a 1.20.1 fabric server and entering some (not all) Illusioner Towers or Labyrinth structures causes both client and server to crash :/

### Crash Report (Required)

https://gist.github.com/MetaForge/73369aa6df89fd923dced49a1f714a51

**Comment by Fuzss** [comment]
Fixed in latest version.
