### ISSUE TITLE
[Suggestion]: Make Protection an imbuable enchantment

### ISSUE THREAD

**Issue by amSnoop** [Fuzss/illagerinvasion#15]
### Suggestion Make Protection Imbuable

Based on what I've read, minecraft can support up to a total Protection level of 20, which would make imbuing 4 armor pieces with Prot 5 a perfect match. I'm a little bit surprised it's not already an imbuable enchantment. If it's not an oversight, why disallow it?

Thanks

**Comment by Ultimushadow** [comment]
Actually I'm surprised this isn't something we can do ourselves, is there any reason the enchantments are not on the config list? I see that you use a tag for all the enchantments, are we meant to create a datapack in that case? As much as I like datapacks, I think that both access to and use of config is way easier, from a user perspective. I would suggest putting the current list in the Imbuement tag into a config option and having the tag provider just read from there. It makes it much easier to add or remove enchantments - not only for personal preference (for vanilla enchants) but also for mod compatibility!

**Comment by Fuzss** [comment]
This was fixed a while ago already, thanks for reporting!

@Ultimushadow Maybe look into KubeJS, I heard it can generate a data pack for you which is controlled via scripts which makes it much simpler than the vanilla approach of having to manually create a bunch of files.
