### ISSUE TITLE
[Bug]: UNPLAYABLE BUG

### ISSUE THREAD

**Issue by SafeOfArsenal** [Fuzss/illagerinvasion#21]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.2

### Notes (Required)

THE NECROMANCER SAYS NECROMANCER EGG INSTEAD OF NECROMANCER SPAWN EGGGGGGGGGGGGGGGG

**Comment by Fuzss** [comment]
This was fixed a while ago already, thanks for reporting! :D
