### ISSUE TITLE
[Crash]: Sorcerer attack crashes server

### ISSUE THREAD

**Issue by NicolasCadre** [Fuzss/illagerinvasion#23]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.2

### Notes (Required)

This crash happen everytime an attacking Sorcerer finished his attack animation.

Don't take into account the multiple fail to load mobs warning in the log, they apparently are related to Friends and Foe mod.

Also the server use Arclight, which allows to uses plugins as well as Forge mods

### Crash Report (Required)

https://gist.github.com/NicolasCadre/fdc1b7fee689f7ded732dfa04e958a6b

### latest.log (Optional)

https://gist.github.com/NicolasCadre/c0e2193474171f4ef608b9c833aad08a

**Comment by Fuzss** [comment]
Yup, seems to be incompatible with Arclight. Not really anything I can do on my end. Report it to them.
