### ISSUE TITLE
[Suggestion]: Allow disabling structures

### ISSUE THREAD

**Issue by spiekermax** [Fuzss/illagerinvasion#27]
### Suggestion

I would like to add the mod to make raids harder, however I don't want the extra structures to spawn in the world.
It would be cool if you could add a configuration that allows to toggle if structures spawn or not.

**Comment by Fuzss** [comment]
You can do that with a data pack, possible the filter section feature.

**Comment by spiekermax** [comment]
Sounds good! Can you provide an example datapack? Maybe I'm doing it wrong but I am not able to prevent the structures from spawning.

**Comment by Fuzss** [comment]
You can find all the information you need here:
https://minecraft.wiki/w/Data_pack#pack.mcmeta
https://minecraft.wiki/w/Java_Edition_22w11a#General
