### ISSUE TITLE
[Suggestion]: Structure spawn rate config

### ISSUE THREAD

**Issue by Kaizuto** [Fuzss/illagerinvasion#28]
### Suggestion (Required)

Idk if its just me but I have this problem where there is illager structure almost everywhere. I'm using tectonic for world gen but this is too many illager structures, would be epic if I could change the generation rate.

**Comment by Fuzss** [comment]
Structure generation is controlled via data packs. The default values are similar to pillager outposts and villages.
You can change the values yourself if the defaults don't work well for your setup.

**Comment by Kaizuto** [comment]
How do i go about doing that?

**Comment by Fuzss** [comment]
Look here at `structure` and `structure_set` and check the wiki for explanations.

https://github.com/Fuzss/illagerinvasion/tree/main/1.20/Forge/src/main/resources/data/illagerinvasion/worldgen
