### ISSUE TITLE
[Crash]: game crashed after a raid started and cant get back into the server

### ISSUE THREAD

**Issue by gnotagnome** [Fuzss/illagerinvasion#29]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v1.20

### Notes (Required)

Im not entirely sure how it happened, I can say that I was in a raid and I was grabbing my stuff from a corpse and now whenever I get into the server the game crashes

### Crash Report (Required)

https://gist.github.com/gnotagnome/003d8543919d17a1173d35a513128c97

**Comment by Xelrox** [comment]
Same here. The proximity to the area of the collision from, it looks like, "Skullbolt" with an item frame, is massive, and causes the server to immediately close. BisectHosting auto restarts bring it to life again, but any time my 2 friends join, the server stops and restarts. They were out exploring together and are thus the only 2 effected, so without them, anyone else can connect and play, and will be fine until they stumble into the area again. I could quarantine the area somehow and clear their data to bring them to spawn but that's extreme. Really hoping for a fix to this soon, really enjoying the mod until this point.

**Comment by RedBeast1959** [comment]
After a few test, I found source of crash. It's Necromancer's skull shape projectile.
When its projectile hits item frame, game instantly crashes.

[crash-2024-01-24_01.19.35-server.txt](https://github.com/Fuzss/illagerinvasion/files/14027190/crash-2024-01-24_01.19.35-server.txt)
