### ISSUE TITLE
[Crash]: With the Archivist pillager

### ISSUE THREAD

**Issue by tealander** [Fuzss/illagerinvasion#30]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.3

### Notes (Required)

1. Find the Archivist pillager
2. Wait him to cast a few spells
3. Your game crashes

### Crash Report (Required)

https://gist.github.com/tealander/8ec500bd1b71062cabac9c814f954fe1

**Comment by Fuzss** [comment]
Update Puzzles Lib to the latest version.
