### ISSUE TITLE
[Bug]: The basement is flooded!!

### ISSUE THREAD

**Issue by TwelveYO21** [Fuzss/illagerinvasion#33]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.4

### Minimal Setup (Required)

Yes

### Notes (Required)

If the area where Illager bases are generated was originally filled with water, the source of water will remain in non-full blocks such as fences and slabs even after the bases are overwritten by generation, resulting in flooding of the entire passage

### latest.log (Required)

No Error

**Comment by TwelveYO21** [comment]
![2024-02-01_17 37 22](https://github.com/Fuzss/illagerinvasion/assets/58351699/ecaf0c12-32b3-4e1f-b422-03384e883903)
![2024-02-01_17 37 36](https://github.com/Fuzss/illagerinvasion/assets/58351699/875baaa5-1450-4082-af3f-3fcfa8579680)

**Comment by viktordimov** [comment]
Seen the same one. Sometimes the labyrinth will spawn over a mountain, fully exposed, or it's dead ends leading to caves.

**Comment by mpustovoi** [comment]
This structure has the function of adjusting the terrain, which leads to the fact that its exposed from mountain parts create a bad-looking cave entrance with many flat plateaus sticking out over the ocean with tunnels, floating 1 block above them.
This structure needs to be redesigned. The entrance on the surface should have terrain correction, but the underground part shouldn't.

**Comment by Fuzss** [comment]
Both the flooding and spawning in mountains with parts of the underground structure are fixed in the latest versions for 1.20.1 and 1.20.4.
