### ISSUE TITLE
[Crash]: crashes on forge 1.20.4

### ISSUE THREAD

**Issue by nickademas** [Fuzss/illagerinvasion#35]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

Forge Config API Port 20.4.3 Illager Invasion 20.4.0 Puzzles Lib 20.4.18

### Minimal Setup

Yes

### Notes (Required)

1. launch the game

### Crash Report (Required)

https://gist.github.com/nickademas/713cc5e1823a488ab0af155ee210b5c9

**Comment by Fuzss** [comment]
Fixed in v20.4.1.
