### ISSUE TITLE
[Bug]: Water flood in mod's added structure

### ISSUE THREAD

**Issue by Anonyku05** [Fuzss/illagerinvasion#42]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

20.4.2

### Minimal Setup (Required)

Yes

### Notes (Required)

The structures added buy the mod have water in the "basement", don't know if this is normal, check the screenshots below:
![image](https://github.com/Fuzss/illagerinvasion/assets/48128391/a3de98e4-0791-4c3c-b9b7-8ef6d3e10bfe)
![image](https://github.com/Fuzss/illagerinvasion/assets/48128391/a478e119-4e3a-411b-8a0e-8c23fb6749cb)

### latest.log (Required)

https://gist.github.com/Anonyku05/2179ddfc6009db4ec27f95e36379350c

**Comment by Fuzss** [comment]
#33
