### ISSUE TITLE
[Bug]: Some chests don't have any stuff in it

### ISSUE THREAD

**Issue by Anonyku05** [Fuzss/illagerinvasion#43]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

20.4.3

### Minimal Setup (Required)

Yes

### Notes (Required)

As said in the title, there are chest that don't have any chest in it, look at the screens below:
![image](https://github.com/Fuzss/illagerinvasion/assets/48128391/c317cb31-4780-457f-94dc-5dcce1871144)
this is the chest down
![image](https://github.com/Fuzss/illagerinvasion/assets/48128391/bdff8d7b-bb0c-41e6-a8b8-7e54d310a8fd)
This is the up chest

### latest.log (Required)

https://gist.github.com/Anonyku05/6e86d4ab7bd12e09b5da21becad550d7

**Comment by Fuzss** [comment]
Thanks, that’s intentional.
