### ISSUE TITLE
[Bug]: Labyrinth hallways are sometimes flooded

### ISSUE THREAD

**Issue by Too-Digital** [Fuzss/illagerinvasion#5]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

When an illager dungeon spawns in underground water pockets, the upside down stairs and fences with torches on them get water logged. Therefore flooding the hallways

**Comment by ImpulsiveLad** [comment]
This is very miserable (and ugly), is there any way to have this fixed soon?
https://streamable.com/tfbgxa

**Comment by xR4YM0ND** [comment]
![2023-10-04_13 49 48](https://github.com/Fuzss/illagerinvasion/assets/97298005/4adc60ad-d162-4908-b9ff-03df2b23d24f)
Same here ... they are waterlogged in water caves

**Comment by Fuzss** [comment]
This was fixed a while ago already, thanks for reporting!
