### ISSUE TITLE
[Bug]: "No data fixer registered for entity" error in logs

### ISSUE THREAD

**Issue by DefinitelyNotFred** [Fuzss/illagerinvasion#50]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.5

### Minimal Setup (Required)

Yes

### Notes (Required)

No other mods installed and had freshly generated config files.

illagerinvasion 8.0.5
puzzleslib 8.1.21
forgeconfigapiport 8.0.0
fabric-api 0.92.2+1.20.1
fabricloader 0.15.11

BTW, you have a minor spelling error in the mod's description on both Curseforge and Modrinth. You start the description for the Illusioner with "Lastely" instead of "Lastly,".

### latest.log (Required)

https://github.com/user-attachments/files/16406716/latest.log

**Comment by Fuzss** [comment]
That's not an issue, just a warning. It's hidden on NeoForge, but Fabric doesn't do that. And thanks!
