### ISSUE TITLE
[Bug]: Missing super call

### ISSUE THREAD

**Issue by someaddons** [Fuzss/illagerinvasion#53]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

any

### Minimal Setup (Required)

Yes

### Notes (Required)

Hi, one of my mods is using onSyncedDataUpdated higher up in the class hierarchy and it breaks with your illusioners, since they're missing the super.onSyncedDataUpdated() call, would be nice if you could add it :)
https://github.com/Fuzss/illagerinvasion/blob/4d0e16201c6d43ccc3269dfb50fd1a767aeeb8d3/1.20.1/Common/src/main/java/fuzs/illagerinvasion/mixin/IllusionerMixin.java#L57

### latest.log (Required)

none

**Comment by Fuzss** [comment]
Fixed, thanks!
