### ISSUE TITLE
[Crash]: Failed to load

### ISSUE THREAD

**Issue by DannyDraconis** [Fuzss/illagerinvasion#56]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

21.1.1

### Minimal Setup

Yes

### Notes (Required)

1 I just open up the Game 

2 I get 
![image](https://github.com/user-attachments/assets/05bcdb4f-91ff-4377-b5e7-1df4e4fd5a73)

I have restarted, cleared logs and cash and config, I also tried making a new profile with just the mods and it still crashes

### Crash Report (Required)

https://gist.github.com/DannyDraconis/12b65494490ba86e39e45404daee64f6

**Comment by Fuzss** [comment]
Fixed in v21.1.2 thanks!
