### ISSUE TITLE
[Minor] [Suggestion]: Add support for NeoForge 21.1.8 ?

### ISSUE THREAD

**Issue by Cixon** [Fuzss/illagerinvasion#63]
### Mod Loader (Optional)

NeoForge

### Minecraft Version(s) (Optional)

1.21.1

### Suggestion (Required)

I'd like to request support for NeoForge 21.1.8 if possible, it would be nice as there's quite a few mods that would be capable of bundling with Swordblocking being one. Thanks!

**Comment by Fuzss** [comment]
Please ask the other mod authors to update instead of asking to downgrade.
