### ISSUE TITLE
[Suggestion]: numismatic overhaul compat.

### ISSUE THREAD

**Issue by Developer2704** [Fuzss/illagerinvasion#8]
### Suggestion (Required)

illagers from illagerinvasion do not drop coins from numismatic overhaul and i contacted its devs but they said it is something that has to be done on your mods side and they told me to link this guide on adding compat. https://docs.wispforest.io/numismatic-overhaul/home/#mob-drops

**Comment by Fuzss** [comment]
thanks, added in latest versions
